import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import { ThemeProvider } from "./context/ThemeContext";
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-slate-100">
        <ThemeProvider>
          <Header />
          <div className="flex">
            <Sidebar />
            <div className="p-8 w-full">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
