// app/layout.jsx

import { useContext } from "react";
import { AuthProvider } from "./context/AuthContext";
import { ThemeProvider } from "./context/ThemeContext";
import "./globals.css";
import LayoutHandler from "./components/Layouts/LayoutHandler";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-slate-100 min-h-screen">
        <AuthProvider>
          <ThemeProvider>
            <LayoutHandler>{children}</LayoutHandler>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
