
export const metadata = {
    title: 'Home',
    description: 'Generated by Next.js',
  }

export default function HomePage() {
    return (
        <div>
            <h2 className="text-2xl font-bold">Home</h2>
            <p>Welcome to the homepage!</p>
        </div>
    );
}
